#include "ch55x/ch554.h"

#include "defs.h"
#include "uart.h"


volatile uint8_t uart0_tx_done = 1;

void uart0_isr(void) __interrupt (INT_NO_UART0)
{
    if(TI) {
        uart0_tx_done = 1;
        TI = 0;
    }
}

// Setup UART0 for baud 57600 generated by timer 1
void uart0_setup(void)
{
    // TODO: Check if pin configuration really is neccessary, or handled by UART0 hardware

    // Setup TX pin P3.1
    P3_DIR_PU |= _BV(1); // Output
    P3_MOD_OC &= ~_BV(1); // Push-pull

    // TODO: setup RX pin P3.0

    // Set UART0 operation: Mode 1 (8-bit, baud rate from T1 or T2)
    SM0 = 0;
    SM1 = 1;
    SM2 = 1; // Use stop bit    

    // Baud generation by T1
    RCLK = 0;
    TCLK = 0;

    // Setup baud rate
    TMOD = (TMOD & 0x0f) | bT1_M1; // Timer 1 mode 2 (8 bit overload/timer), leave Timer 0 untouched
    T2MOD |= bTMR_CLK | bT1_CLK; // No division, fast clock selected
    PCON |= SMOD; // Fast mode
    TH1 = 0xf3; // 256 - Fsys / 16 / baud_rate
    TR1 = 1; // Start timer

    // Reset TX, RX flags
    TI = 0;
    RI = 0;

    // Enable interrupt
    ES = 1;
}

void uart0_block_tx_byte(uint8_t byte)
{
//    TI = 0;
    uart0_tx_done = 0;
    SBUF = byte;
//    while(!TI);
    while(!uart0_tx_done);
}
